package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Attivita generated by hbm2java
 */
public class Attivita  implements java.io.Serializable {


     private Integer id;
     private Avanzamento avanzamento;
     private Servizio servizio;
     private TipoContratto tipoContratto;
     private String coge;
     private String codiceIntevento;
     private String ywattDescsAreacontr;
     private String ywattDescsAreaapp;
     private String ywattDescsAreainps;
     private String ywattDenomAmbapp;
     private String ywattCodDirezione;
     private String ywattDenomLineaint;
     private String ywattDescsAmbfunz;
     private String ywattCodPianoforn;
     private String codiceGeco;
     private String nomeScheda;
     private String ywattDescrProgetto;
     private String ywattDenomRespinps;
     private String ywattDenomRefinps;
     private String ywattDescsServizio;
     private String ywattDenomTipserv;
     private String ywattDenomCapprg;
     private String ywattDenomCapprgrif;
     private String ywattCodStatolav;
     private Date ywattDataApertssu;
     private Date ywattDataChiusssu;
     private String ywattDataRipianwbs;
     private String ywattNumSemattivaz;
     private Date ywattDataConsrqpian;
     private Date ywattDataConsrqeff;
     private Date ywattDataCollpian;
     private Date ywattDataColleff;
     private Date ywattDataInizcoll;
     private Date ywattDataFinecoll;
     private Date ywattDataAvveseeff;
     private String ywattCodTipoint;
     private String ywattNoteTecniche;
     private String ywattNoteGenerali;
     private String ywattDescrScadist;
     private String ywattNumId;
     private String ywattNumPriorita;
     private String ywattDescsMacroatt;
     private Boolean ywattDescsPrescoge;
     private String ywattDataSal;
     private String ywattImpConsuntivo;
     private Integer ywattPercFasecons;
     private Date created;
     private Date updated;
     private String user;
     private Set<Task> tasks = new HashSet<Task>(0);
     private Set<ValoreEconomico> valoreEconomicos = new HashSet<ValoreEconomico>(0);

    public Attivita() {
    }

	
    public Attivita(Servizio servizio, TipoContratto tipoContratto, Date created, Date updated) {
        this.servizio = servizio;
        this.tipoContratto = tipoContratto;
        this.created = created;
        this.updated = updated;
    }
    public Attivita(Avanzamento avanzamento, Servizio servizio, TipoContratto tipoContratto, String coge, String codiceIntevento, String ywattDescsAreacontr, String ywattDescsAreaapp, String ywattDescsAreainps, String ywattDenomAmbapp, String ywattCodDirezione, String ywattDenomLineaint, String ywattDescsAmbfunz, String ywattCodPianoforn, String codiceGeco, String nomeScheda, String ywattDescrProgetto, String ywattDenomRespinps, String ywattDenomRefinps, String ywattDescsServizio, String ywattDenomTipserv, String ywattDenomCapprg, String ywattDenomCapprgrif, String ywattCodStatolav, Date ywattDataApertssu, Date ywattDataChiusssu, String ywattDataRipianwbs, String ywattNumSemattivaz, Date ywattDataConsrqpian, Date ywattDataConsrqeff, Date ywattDataCollpian, Date ywattDataColleff, Date ywattDataInizcoll, Date ywattDataFinecoll, Date ywattDataAvveseeff, String ywattCodTipoint, String ywattNoteTecniche, String ywattNoteGenerali, String ywattDescrScadist, String ywattNumId, String ywattNumPriorita, String ywattDescsMacroatt, Boolean ywattDescsPrescoge, String ywattDataSal, String ywattImpConsuntivo, Integer ywattPercFasecons, Date created, Date updated, String user, Set<Task> tasks, Set<ValoreEconomico> valoreEconomicos) {
       this.avanzamento = avanzamento;
       this.servizio = servizio;
       this.tipoContratto = tipoContratto;
       this.coge = coge;
       this.codiceIntevento = codiceIntevento;
       this.ywattDescsAreacontr = ywattDescsAreacontr;
       this.ywattDescsAreaapp = ywattDescsAreaapp;
       this.ywattDescsAreainps = ywattDescsAreainps;
       this.ywattDenomAmbapp = ywattDenomAmbapp;
       this.ywattCodDirezione = ywattCodDirezione;
       this.ywattDenomLineaint = ywattDenomLineaint;
       this.ywattDescsAmbfunz = ywattDescsAmbfunz;
       this.ywattCodPianoforn = ywattCodPianoforn;
       this.codiceGeco = codiceGeco;
       this.nomeScheda = nomeScheda;
       this.ywattDescrProgetto = ywattDescrProgetto;
       this.ywattDenomRespinps = ywattDenomRespinps;
       this.ywattDenomRefinps = ywattDenomRefinps;
       this.ywattDescsServizio = ywattDescsServizio;
       this.ywattDenomTipserv = ywattDenomTipserv;
       this.ywattDenomCapprg = ywattDenomCapprg;
       this.ywattDenomCapprgrif = ywattDenomCapprgrif;
       this.ywattCodStatolav = ywattCodStatolav;
       this.ywattDataApertssu = ywattDataApertssu;
       this.ywattDataChiusssu = ywattDataChiusssu;
       this.ywattDataRipianwbs = ywattDataRipianwbs;
       this.ywattNumSemattivaz = ywattNumSemattivaz;
       this.ywattDataConsrqpian = ywattDataConsrqpian;
       this.ywattDataConsrqeff = ywattDataConsrqeff;
       this.ywattDataCollpian = ywattDataCollpian;
       this.ywattDataColleff = ywattDataColleff;
       this.ywattDataInizcoll = ywattDataInizcoll;
       this.ywattDataFinecoll = ywattDataFinecoll;
       this.ywattDataAvveseeff = ywattDataAvveseeff;
       this.ywattCodTipoint = ywattCodTipoint;
       this.ywattNoteTecniche = ywattNoteTecniche;
       this.ywattNoteGenerali = ywattNoteGenerali;
       this.ywattDescrScadist = ywattDescrScadist;
       this.ywattNumId = ywattNumId;
       this.ywattNumPriorita = ywattNumPriorita;
       this.ywattDescsMacroatt = ywattDescsMacroatt;
       this.ywattDescsPrescoge = ywattDescsPrescoge;
       this.ywattDataSal = ywattDataSal;
       this.ywattImpConsuntivo = ywattImpConsuntivo;
       this.ywattPercFasecons = ywattPercFasecons;
       this.created = created;
       this.updated = updated;
       this.user = user;
       this.tasks = tasks;
       this.valoreEconomicos = valoreEconomicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Avanzamento getAvanzamento() {
        return this.avanzamento;
    }
    
    public void setAvanzamento(Avanzamento avanzamento) {
        this.avanzamento = avanzamento;
    }
    public Servizio getServizio() {
        return this.servizio;
    }
    
    public void setServizio(Servizio servizio) {
        this.servizio = servizio;
    }
    public TipoContratto getTipoContratto() {
        return this.tipoContratto;
    }
    
    public void setTipoContratto(TipoContratto tipoContratto) {
        this.tipoContratto = tipoContratto;
    }
    public String getCoge() {
        return this.coge;
    }
    
    public void setCoge(String coge) {
        this.coge = coge;
    }
    public String getCodiceIntevento() {
        return this.codiceIntevento;
    }
    
    public void setCodiceIntevento(String codiceIntevento) {
        this.codiceIntevento = codiceIntevento;
    }
    public String getYwattDescsAreacontr() {
        return this.ywattDescsAreacontr;
    }
    
    public void setYwattDescsAreacontr(String ywattDescsAreacontr) {
        this.ywattDescsAreacontr = ywattDescsAreacontr;
    }
    public String getYwattDescsAreaapp() {
        return this.ywattDescsAreaapp;
    }
    
    public void setYwattDescsAreaapp(String ywattDescsAreaapp) {
        this.ywattDescsAreaapp = ywattDescsAreaapp;
    }
    public String getYwattDescsAreainps() {
        return this.ywattDescsAreainps;
    }
    
    public void setYwattDescsAreainps(String ywattDescsAreainps) {
        this.ywattDescsAreainps = ywattDescsAreainps;
    }
    public String getYwattDenomAmbapp() {
        return this.ywattDenomAmbapp;
    }
    
    public void setYwattDenomAmbapp(String ywattDenomAmbapp) {
        this.ywattDenomAmbapp = ywattDenomAmbapp;
    }
    public String getYwattCodDirezione() {
        return this.ywattCodDirezione;
    }
    
    public void setYwattCodDirezione(String ywattCodDirezione) {
        this.ywattCodDirezione = ywattCodDirezione;
    }
    public String getYwattDenomLineaint() {
        return this.ywattDenomLineaint;
    }
    
    public void setYwattDenomLineaint(String ywattDenomLineaint) {
        this.ywattDenomLineaint = ywattDenomLineaint;
    }
    public String getYwattDescsAmbfunz() {
        return this.ywattDescsAmbfunz;
    }
    
    public void setYwattDescsAmbfunz(String ywattDescsAmbfunz) {
        this.ywattDescsAmbfunz = ywattDescsAmbfunz;
    }
    public String getYwattCodPianoforn() {
        return this.ywattCodPianoforn;
    }
    
    public void setYwattCodPianoforn(String ywattCodPianoforn) {
        this.ywattCodPianoforn = ywattCodPianoforn;
    }
    public String getCodiceGeco() {
        return this.codiceGeco;
    }
    
    public void setCodiceGeco(String codiceGeco) {
        this.codiceGeco = codiceGeco;
    }
    public String getNomeScheda() {
        return this.nomeScheda;
    }
    
    public void setNomeScheda(String nomeScheda) {
        this.nomeScheda = nomeScheda;
    }
    public String getYwattDescrProgetto() {
        return this.ywattDescrProgetto;
    }
    
    public void setYwattDescrProgetto(String ywattDescrProgetto) {
        this.ywattDescrProgetto = ywattDescrProgetto;
    }
    public String getYwattDenomRespinps() {
        return this.ywattDenomRespinps;
    }
    
    public void setYwattDenomRespinps(String ywattDenomRespinps) {
        this.ywattDenomRespinps = ywattDenomRespinps;
    }
    public String getYwattDenomRefinps() {
        return this.ywattDenomRefinps;
    }
    
    public void setYwattDenomRefinps(String ywattDenomRefinps) {
        this.ywattDenomRefinps = ywattDenomRefinps;
    }
    public String getYwattDescsServizio() {
        return this.ywattDescsServizio;
    }
    
    public void setYwattDescsServizio(String ywattDescsServizio) {
        this.ywattDescsServizio = ywattDescsServizio;
    }
    public String getYwattDenomTipserv() {
        return this.ywattDenomTipserv;
    }
    
    public void setYwattDenomTipserv(String ywattDenomTipserv) {
        this.ywattDenomTipserv = ywattDenomTipserv;
    }
    public String getYwattDenomCapprg() {
        return this.ywattDenomCapprg;
    }
    
    public void setYwattDenomCapprg(String ywattDenomCapprg) {
        this.ywattDenomCapprg = ywattDenomCapprg;
    }
    public String getYwattDenomCapprgrif() {
        return this.ywattDenomCapprgrif;
    }
    
    public void setYwattDenomCapprgrif(String ywattDenomCapprgrif) {
        this.ywattDenomCapprgrif = ywattDenomCapprgrif;
    }
    public String getYwattCodStatolav() {
        return this.ywattCodStatolav;
    }
    
    public void setYwattCodStatolav(String ywattCodStatolav) {
        this.ywattCodStatolav = ywattCodStatolav;
    }
    public Date getYwattDataApertssu() {
        return this.ywattDataApertssu;
    }
    
    public void setYwattDataApertssu(Date ywattDataApertssu) {
        this.ywattDataApertssu = ywattDataApertssu;
    }
    public Date getYwattDataChiusssu() {
        return this.ywattDataChiusssu;
    }
    
    public void setYwattDataChiusssu(Date ywattDataChiusssu) {
        this.ywattDataChiusssu = ywattDataChiusssu;
    }
    public String getYwattDataRipianwbs() {
        return this.ywattDataRipianwbs;
    }
    
    public void setYwattDataRipianwbs(String ywattDataRipianwbs) {
        this.ywattDataRipianwbs = ywattDataRipianwbs;
    }
    public String getYwattNumSemattivaz() {
        return this.ywattNumSemattivaz;
    }
    
    public void setYwattNumSemattivaz(String ywattNumSemattivaz) {
        this.ywattNumSemattivaz = ywattNumSemattivaz;
    }
    public Date getYwattDataConsrqpian() {
        return this.ywattDataConsrqpian;
    }
    
    public void setYwattDataConsrqpian(Date ywattDataConsrqpian) {
        this.ywattDataConsrqpian = ywattDataConsrqpian;
    }
    public Date getYwattDataConsrqeff() {
        return this.ywattDataConsrqeff;
    }
    
    public void setYwattDataConsrqeff(Date ywattDataConsrqeff) {
        this.ywattDataConsrqeff = ywattDataConsrqeff;
    }
    public Date getYwattDataCollpian() {
        return this.ywattDataCollpian;
    }
    
    public void setYwattDataCollpian(Date ywattDataCollpian) {
        this.ywattDataCollpian = ywattDataCollpian;
    }
    public Date getYwattDataColleff() {
        return this.ywattDataColleff;
    }
    
    public void setYwattDataColleff(Date ywattDataColleff) {
        this.ywattDataColleff = ywattDataColleff;
    }
    public Date getYwattDataInizcoll() {
        return this.ywattDataInizcoll;
    }
    
    public void setYwattDataInizcoll(Date ywattDataInizcoll) {
        this.ywattDataInizcoll = ywattDataInizcoll;
    }
    public Date getYwattDataFinecoll() {
        return this.ywattDataFinecoll;
    }
    
    public void setYwattDataFinecoll(Date ywattDataFinecoll) {
        this.ywattDataFinecoll = ywattDataFinecoll;
    }
    public Date getYwattDataAvveseeff() {
        return this.ywattDataAvveseeff;
    }
    
    public void setYwattDataAvveseeff(Date ywattDataAvveseeff) {
        this.ywattDataAvveseeff = ywattDataAvveseeff;
    }
    public String getYwattCodTipoint() {
        return this.ywattCodTipoint;
    }
    
    public void setYwattCodTipoint(String ywattCodTipoint) {
        this.ywattCodTipoint = ywattCodTipoint;
    }
    public String getYwattNoteTecniche() {
        return this.ywattNoteTecniche;
    }
    
    public void setYwattNoteTecniche(String ywattNoteTecniche) {
        this.ywattNoteTecniche = ywattNoteTecniche;
    }
    public String getYwattNoteGenerali() {
        return this.ywattNoteGenerali;
    }
    
    public void setYwattNoteGenerali(String ywattNoteGenerali) {
        this.ywattNoteGenerali = ywattNoteGenerali;
    }
    public String getYwattDescrScadist() {
        return this.ywattDescrScadist;
    }
    
    public void setYwattDescrScadist(String ywattDescrScadist) {
        this.ywattDescrScadist = ywattDescrScadist;
    }
    public String getYwattNumId() {
        return this.ywattNumId;
    }
    
    public void setYwattNumId(String ywattNumId) {
        this.ywattNumId = ywattNumId;
    }
    public String getYwattNumPriorita() {
        return this.ywattNumPriorita;
    }
    
    public void setYwattNumPriorita(String ywattNumPriorita) {
        this.ywattNumPriorita = ywattNumPriorita;
    }
    public String getYwattDescsMacroatt() {
        return this.ywattDescsMacroatt;
    }
    
    public void setYwattDescsMacroatt(String ywattDescsMacroatt) {
        this.ywattDescsMacroatt = ywattDescsMacroatt;
    }
    public Boolean getYwattDescsPrescoge() {
        return this.ywattDescsPrescoge;
    }
    
    public void setYwattDescsPrescoge(Boolean ywattDescsPrescoge) {
        this.ywattDescsPrescoge = ywattDescsPrescoge;
    }
    public String getYwattDataSal() {
        return this.ywattDataSal;
    }
    
    public void setYwattDataSal(String ywattDataSal) {
        this.ywattDataSal = ywattDataSal;
    }
    public String getYwattImpConsuntivo() {
        return this.ywattImpConsuntivo;
    }
    
    public void setYwattImpConsuntivo(String ywattImpConsuntivo) {
        this.ywattImpConsuntivo = ywattImpConsuntivo;
    }
    public Integer getYwattPercFasecons() {
        return this.ywattPercFasecons;
    }
    
    public void setYwattPercFasecons(Integer ywattPercFasecons) {
        this.ywattPercFasecons = ywattPercFasecons;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }
    public Set<ValoreEconomico> getValoreEconomicos() {
        return this.valoreEconomicos;
    }
    
    public void setValoreEconomicos(Set<ValoreEconomico> valoreEconomicos) {
        this.valoreEconomicos = valoreEconomicos;
    }




}


