package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;

/**
 * AttivitaView generated by hbm2java
 */
public class AttivitaView  implements java.io.Serializable {


     private Integer id;
     private String codiceTipoContratto;
     private String codiceServizio;
     private String codiceIntervento;
     private String codiceGecoSSU;
     private String nomeScheda;
     private long numeroTask;
     private BigDecimal totalEffort;

    public AttivitaView() {
    }

	
    public AttivitaView(Integer id, String codiceTipoContratto, String codiceServizio, long numeroTask, BigDecimal totalEffort) {
        this.id = id;
        this.codiceTipoContratto = codiceTipoContratto;
        this.codiceServizio = codiceServizio;
        this.numeroTask = numeroTask;
        this.totalEffort = totalEffort;
    }
    public AttivitaView(Integer id, String codiceTipoContratto, String codiceServizio, String codiceIntervento, String codiceGecoSSU, String nomeScheda, long numeroTask, BigDecimal totalEffort) {
       this.id = id;
       this.codiceTipoContratto = codiceTipoContratto;
       this.codiceServizio = codiceServizio;
       this.codiceIntervento = codiceIntervento;
       this.codiceGecoSSU = codiceGecoSSU;
       this.nomeScheda = nomeScheda;
       this.numeroTask = numeroTask;
       this.totalEffort = totalEffort;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodiceTipoContratto() {
        return this.codiceTipoContratto;
    }
    
    public void setCodiceTipoContratto(String codiceTipoContratto) {
        this.codiceTipoContratto = codiceTipoContratto;
    }
    public String getCodiceServizio() {
        return this.codiceServizio;
    }
    
    public void setCodiceServizio(String codiceServizio) {
        this.codiceServizio = codiceServizio;
    }
    public String getCodiceIntervento() {
        return this.codiceIntervento;
    }
    
    public void setCodiceIntervento(String codiceIntervento) {
        this.codiceIntervento = codiceIntervento;
    }
    public String getCodiceGecoSSU() {
        return this.codiceGecoSSU;
    }
    
    public void setCodiceGecoSSU(String codiceGecoSSU) {
        this.codiceGecoSSU = codiceGecoSSU;
    }
    public String getNomeScheda() {
        return this.nomeScheda;
    }
    
    public void setNomeScheda(String nomeScheda) {
        this.nomeScheda = nomeScheda;
    }
    public long getNumeroTask() {
        return this.numeroTask;
    }
    
    public void setNumeroTask(long numeroTask) {
        this.numeroTask = numeroTask;
    }
    public BigDecimal getTotalEffort() {
        return this.totalEffort;
    }
    
    public void setTotalEffort(BigDecimal totalEffort) {
        this.totalEffort = totalEffort;
    }




}


