package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Avanzamento generated by hbm2java
 */
public class Avanzamento  implements java.io.Serializable {


     private Integer id;
     private String descrizioneGeco;
     private String descrizioneAlmaviva;
     private String descrizione;
     private Date created;
     private Date updated;
     private String user;
     private Set<Attivita> attivitas = new HashSet<Attivita>(0);

    public Avanzamento() {
    }

	
    public Avanzamento(String descrizione, Date created, Date updated) {
        this.descrizione = descrizione;
        this.created = created;
        this.updated = updated;
    }
    public Avanzamento(String descrizioneGeco, String descrizioneAlmaviva, String descrizione, Date created, Date updated, String user, Set<Attivita> attivitas) {
       this.descrizioneGeco = descrizioneGeco;
       this.descrizioneAlmaviva = descrizioneAlmaviva;
       this.descrizione = descrizione;
       this.created = created;
       this.updated = updated;
       this.user = user;
       this.attivitas = attivitas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescrizioneGeco() {
        return this.descrizioneGeco;
    }
    
    public void setDescrizioneGeco(String descrizioneGeco) {
        this.descrizioneGeco = descrizioneGeco;
    }
    public String getDescrizioneAlmaviva() {
        return this.descrizioneAlmaviva;
    }
    
    public void setDescrizioneAlmaviva(String descrizioneAlmaviva) {
        this.descrizioneAlmaviva = descrizioneAlmaviva;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Set<Attivita> getAttivitas() {
        return this.attivitas;
    }
    
    public void setAttivitas(Set<Attivita> attivitas) {
        this.attivitas = attivitas;
    }




}


