package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set<TipoTask> tipoTasks = new HashSet<TipoTask>(0);

    public Tag() {
    }

	
    public Tag(String value) {
        this.value = value;
    }
    public Tag(String value, Set<TipoTask> tipoTasks) {
       this.value = value;
       this.tipoTasks = tipoTasks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set<TipoTask> getTipoTasks() {
        return this.tipoTasks;
    }
    
    public void setTipoTasks(Set<TipoTask> tipoTasks) {
        this.tipoTasks = tipoTasks;
    }




}


