package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private Integer id;
     private Attivita attivita;
     private TipoTask tipoTask;
     private String nota;
     private Integer effort;
     private Date created;
     private Date updated;
     private String user;
     private Set<Attachment> attachments = new HashSet<Attachment>(0);

    public Task() {
    }

	
    public Task(Attivita attivita, TipoTask tipoTask, String nota, Date created, Date updated) {
        this.attivita = attivita;
        this.tipoTask = tipoTask;
        this.nota = nota;
        this.created = created;
        this.updated = updated;
    }
    public Task(Attivita attivita, TipoTask tipoTask, String nota, Integer effort, Date created, Date updated, String user, Set<Attachment> attachments) {
       this.attivita = attivita;
       this.tipoTask = tipoTask;
       this.nota = nota;
       this.effort = effort;
       this.created = created;
       this.updated = updated;
       this.user = user;
       this.attachments = attachments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Attivita getAttivita() {
        return this.attivita;
    }
    
    public void setAttivita(Attivita attivita) {
        this.attivita = attivita;
    }
    public TipoTask getTipoTask() {
        return this.tipoTask;
    }
    
    public void setTipoTask(TipoTask tipoTask) {
        this.tipoTask = tipoTask;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public Integer getEffort() {
        return this.effort;
    }
    
    public void setEffort(Integer effort) {
        this.effort = effort;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Set<Attachment> getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(Set<Attachment> attachments) {
        this.attachments = attachments;
    }




}


