package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoValoreEconomico generated by hbm2java
 */
public class TipoValoreEconomico  implements java.io.Serializable {


     private Integer id;
     private String codice;
     private String descrizione;
     private Date created;
     private Date updated;
     private String user;
     private Set<ValoreEconomico> valoreEconomicos = new HashSet<ValoreEconomico>(0);

    public TipoValoreEconomico() {
    }

	
    public TipoValoreEconomico(String codice, String descrizione, Date created, Date updated) {
        this.codice = codice;
        this.descrizione = descrizione;
        this.created = created;
        this.updated = updated;
    }
    public TipoValoreEconomico(String codice, String descrizione, Date created, Date updated, String user, Set<ValoreEconomico> valoreEconomicos) {
       this.codice = codice;
       this.descrizione = descrizione;
       this.created = created;
       this.updated = updated;
       this.user = user;
       this.valoreEconomicos = valoreEconomicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Set<ValoreEconomico> getValoreEconomicos() {
        return this.valoreEconomicos;
    }
    
    public void setValoreEconomicos(Set<ValoreEconomico> valoreEconomicos) {
        this.valoreEconomicos = valoreEconomicos;
    }




}


