package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoContratto generated by hbm2java
 */
public class TipoContratto  implements java.io.Serializable {


     private Integer id;
     private String codice;
     private String descrizione;
     private Date created;
     private Date updated;
     private String user;
     private Set<Attivita> attivitas = new HashSet<Attivita>(0);
     private Set<Servizio> servizios = new HashSet<Servizio>(0);

    public TipoContratto() {
    }

	
    public TipoContratto(String codice, String descrizione, Date created, Date updated) {
        this.codice = codice;
        this.descrizione = descrizione;
        this.created = created;
        this.updated = updated;
    }
    public TipoContratto(String codice, String descrizione, Date created, Date updated, String user, Set<Attivita> attivitas, Set<Servizio> servizios) {
       this.codice = codice;
       this.descrizione = descrizione;
       this.created = created;
       this.updated = updated;
       this.user = user;
       this.attivitas = attivitas;
       this.servizios = servizios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Set<Attivita> getAttivitas() {
        return this.attivitas;
    }
    
    public void setAttivitas(Set<Attivita> attivitas) {
        this.attivitas = attivitas;
    }
    public Set<Servizio> getServizios() {
        return this.servizios;
    }
    
    public void setServizios(Set<Servizio> servizios) {
        this.servizios = servizios;
    }




}


