package it.inps.bricks.model;
// Generated 27-gen-2017 16.29.52 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;

/**
 * ValoreEconomico generated by hbm2java
 */
public class ValoreEconomico  implements java.io.Serializable {


     private Integer id;
     private Attivita attivita;
     private TipoValoreEconomico tipoValoreEconomico;
     private Integer fte;
     private String fpe;
     private Integer add;
     private Integer chg;
     private String del;
     private Date created;
     private Date updated;
     private String user;

    public ValoreEconomico() {
    }

	
    public ValoreEconomico(Attivita attivita, TipoValoreEconomico tipoValoreEconomico, Integer fte, Date created, Date updated) {
        this.attivita = attivita;
        this.tipoValoreEconomico = tipoValoreEconomico;
        this.fte = fte;
        this.created = created;
        this.updated = updated;
    }
    public ValoreEconomico(Attivita attivita, TipoValoreEconomico tipoValoreEconomico, Integer fte, String fpe, Integer add, Integer chg, String del, Date created, Date updated, String user) {
       this.attivita = attivita;
       this.tipoValoreEconomico = tipoValoreEconomico;
       this.fte = fte;
       this.fpe = fpe;
       this.add = add;
       this.chg = chg;
       this.del = del;
       this.created = created;
       this.updated = updated;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Attivita getAttivita() {
        return this.attivita;
    }
    
    public void setAttivita(Attivita attivita) {
        this.attivita = attivita;
    }
    public TipoValoreEconomico getTipoValoreEconomico() {
        return this.tipoValoreEconomico;
    }
    
    public void setTipoValoreEconomico(TipoValoreEconomico tipoValoreEconomico) {
        this.tipoValoreEconomico = tipoValoreEconomico;
    }
    public Integer getFte() {
        return this.fte;
    }
    
    public void setFte(Integer fte) {
        this.fte = fte;
    }
    public String getFpe() {
        return this.fpe;
    }
    
    public void setFpe(String fpe) {
        this.fpe = fpe;
    }
    public Integer getAdd() {
        return this.add;
    }
    
    public void setAdd(Integer add) {
        this.add = add;
    }
    public Integer getChg() {
        return this.chg;
    }
    
    public void setChg(Integer chg) {
        this.chg = chg;
    }
    public String getDel() {
        return this.del;
    }
    
    public void setDel(String del) {
        this.del = del;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }




}


